# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='when_sent',
            new_name='when',
        ),
        migrations.RenameField(
            model_name='messagethread',
            old_name='when_sent',
            new_name='when',
        ),
    ]
