# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20170629_0534'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
