# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0006_auto_20170629_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagecopied', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='content',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='when',
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='_thread', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='copymessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.Message'),
        ),
        migrations.AddField(
            model_name='copymessage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copymessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread2', to='messaging.MessageThread'),
        ),
    ]
