# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20170630_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagethread',
            name='participants',
            field=models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
