# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20170630_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copymessage',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
    ]
